### ISSUE TITLE
Game Crash when closing laptop

### ISSUE THREAD

**Issue by Hubcapp** [OrN/rscplus#21]
Looks like a Jagex bug, not the RSC+, but since #3 is open and Jagex will never update RS1 again, I figure it's fine to report this here.

Crash 1:
Error: ua.RA({...},0,256,0) client.R(2540) client.JD(false) | Game.Renderer.present ua.a client.k client.b e.run java.lang.Thread.run:745 | java.lang.NullPointerException
error_game_crash

Crash 2:
Error: ua.RA({...},0,256,0) client.R(2540) client.JD(false) | | java.lang.NullPointerException
error_game_crash

crash 3:
Network connection issues
java.net.UnknownHostException: www.runescape.com
    at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:178)
    at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
    at java.net.Socket.connect(Socket.java:579)
    at java.net.Socket.connect(Socket.java:528)
    at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
    at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
    at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
    at sun.net.www.http.HttpClient.<init>(HttpClient.java:211)
    at sun.net.www.http.HttpClient.New(HttpClient.java:308)
    at sun.net.www.http.HttpClient.New(HttpClient.java:326)
    at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:998)
    at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:934)
    at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:852)
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1302)
    at Client.Util.getPop(Unknown Source)
    at Game.Renderer.present(Unknown Source)
    at ua.a(Unknown Source)
    at client.k(Unknown Source)
    at client.b(Unknown Source)
    at e.run(Unknown Source)
    at java.lang.Thread.run(Thread.java:745)
Error: ua.RA({...},0,256,0) client.R(2540) client.JD(false) | Game.Renderer.present ua.a client.k client.b e.run java.lang.Thread.run:745 | java.lang.NullPointerException
error_game_crash

To reproduce: 
1. disconnect from the internet while playing (not sure this step is necessary)
2. return to login screen
3. change workplaces (minimize maximize on windows? not sure this step is necessary to get the crash)

It might also be caused by just waiting at login screen until it tries to do something networky.

**Comment by Hubcapp** [comment]
Probably solved by #36!
