### ISSUE TITLE
Error: Unable to fetch Jar

### ISSUE THREAD

**Issue by mft004** [OrN/rscplus#44]
That's the error message I get, followed by "Error: unable to launch game" when I open rscplus.jar; what should I do?

Thanks for any advice

**Comment by thelegendofbrian** [comment]
It appears that the jar file that is normally downloaded via Dropbox is missing. I'm assuming that @OrN hosts that jar. Any chance you could take a look at that for us @OrN?

The following is the console error:

```
[ INFO] Loading resource: /assets/icon.png
[ INFO] Fetching Jar: https://dl.dropboxusercontent.com/u/61045381/rscplus/rsc_234.jar
java.io.FileNotFoundException: https://dl.dropboxusercontent.com/u/61045381/rscplus/rsc_234.jar
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source)
        at Client.JClassLoader.fetch(Unknown Source)
        at Client.Launcher.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
java.lang.NullPointerException
        at Client.Launcher.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
```

**Comment by mft004** [comment]
Thanks for the extra info Brian, not in a desperate rush to use rsc+ but as soon as it's back I'll be back to using it again, the extra field of view it offers is just invaluable.

**Comment by OrN** [comment]
It should be fixed in latest now, I'll fix it properly when I get back to my pc.

**Comment by mft004** [comment]
Yep I can report that it's working again now, many thanks OrN, good to be back on rsc+ :)
