### ISSUE TITLE
Crash when running rscplus with Java 9 (does 10 work?)

### ISSUE THREAD

**Issue by thelegendofbrian** [OrN/rscplus#53]
A user reported a crash upon loading the game.

```
java version "9.0.1"
Java(TM) SE Runtime Environment (build 9.0.1+11)
Java HotSpot(TM) 64-Bit Server VM (build 9.0.1+11, mixed mode)
```

```
[ INFO] Jar Location: /C:/Users/Redacted/Desktop/rscplus
[ INFO] Creating configuration window
[ INFO] Loading resource: /assets/icon.png
[ INFO] Loading resource: /assets/icon-small.gif
[ INFO] Creating notification window
[ INFO] Loading resource: /assets/icon.png
[ INFO] Loading resource: /assets/notification_close.png
[ INFO] Loading resource: /assets/notification_close_highlighted.png
[ INFO] Loading resource: /assets/notification_background.png
[ INFO] Loading resource as stream: /assets/OpenSans-Regular.ttf
[ INFO] Loading resource as stream: /assets/OpenSans-Bold.ttf
[ INFO] Loading resource as stream: /assets/notification.wav
[ INFO] Starting rscplus
[ INFO] Loading resource: /assets/icon.png
[ INFO] Fetching Jar: /assets/rsc.jar
[ INFO] Loading resource as stream: /assets/rsc.jar
[ INFO] Loading file: a.class
[ INFO] Loading file: aa.class
[ INFO] Loading file: ab.class
[ INFO] Loading file: ac.class
[ INFO] Loading file: b.class
[ INFO] Loading file: ba.class
[ INFO] Loading file: bb.class
[ INFO] Loading file: c.class
[ INFO] Loading file: ca.class
[ INFO] Loading file: cb.class
[ INFO] Loading file: client.class
[ INFO] Patching client (client.class)
[ INFO] Loading file: d.class
[ INFO] Loading file: da.class
[ INFO] Loading file: db.class
[ INFO] Loading file: e.class
[ INFO] Patching applet (e.class)
[ INFO] Loading file: ea.class
[ INFO] Loading file: eb.class
[ INFO] Loading file: f.class
[ INFO] Patching random (f.class)
Patching validation...
[ INFO] Loading file: fa.class
[ INFO] Loading file: fb.class
[ INFO] Loading file: g.class
[ INFO] Loading file: ga.class
[ INFO] Loading file: gb.class
[ INFO] Loading file: h.class
[ INFO] Loading file: ha.class
[ INFO] Loading file: hb.class
[ INFO] Loading file: i.class
[ INFO] Loading file: ia.class
[ INFO] Loading file: ib.class
[ INFO] Loading file: j.class
[ INFO] Loading file: ja.class
[ INFO] Loading file: jb.class
[ INFO] Loading file: k.class
[ INFO] Loading file: ka.class
[ INFO] Loading file: kb.class
[ INFO] Loading file: l.class
[ INFO] Loading file: la.class
[ INFO] Loading file: lb.class
[ INFO] Loading file: m.class
[ INFO] Patching data (m.class)
[ INFO] Loading file: ma.class
[ INFO] Loading file: mb.class
[ INFO] Loading file: n.class
[ INFO] Loading file: na.class
[ INFO] Loading file: nb.class
[ INFO] Loading file: o.class
[ INFO] Loading file: oa.class
[ INFO] Loading file: ob.class
[ INFO] Loading file: p.class
[ INFO] Loading file: pa.class
[ INFO] Loading file: pb.class
[ INFO] Loading file: q.class
[ INFO] Loading file: qa.class
[ INFO] Patching menu (qa.class)
[ INFO] Loading file: qb.class
[ INFO] Loading file: r.class
[ INFO] Loading file: ra.class
[ INFO] Loading file: rb.class
[ INFO] Loading file: s.class
[ INFO] Loading file: sa.class
[ INFO] Loading file: sb.class
[ INFO] Loading file: t.class
[ INFO] Loading file: ta.class
[ INFO] Loading file: tb.class
[ INFO] Loading file: u.class
[ INFO] Loading file: ua.class
[ INFO] Patching renderer (ua.class)
[ INFO] Loading file: ub.class
[ INFO] Loading file: v.class
[ INFO] Loading file: va.class
[ INFO] Loading file: vb.class
[ INFO] Loading file: w.class
[ INFO] Loading file: wa.class
[ INFO] Loading file: wb.class
[ INFO] Loading resource: /assets/icon.png
Exception in thread "Thread-1" java.lang.NoSuchMethodError: java.applet.Applet.getPeer()Ljava/awt/peer/ComponentPeer;
        at e.isDisplayable(Unknown Source)
        at java.desktop/java.awt.Container.increaseComponentCount(Unknown Source)
        at java.desktop/java.awt.Component.addNotify(Unknown Source)
        at java.desktop/java.awt.Container.addNotify(Unknown Source)
        at java.desktop/java.awt.Panel.addNotify(Unknown Source)
        at java.desktop/java.awt.Container.addNotify(Unknown Source)
        at java.desktop/javax.swing.JComponent.addNotify(Unknown Source)
        at java.desktop/java.awt.Container.addNotify(Unknown Source)
        at java.desktop/javax.swing.JComponent.addNotify(Unknown Source)
        at java.desktop/javax.swing.JRootPane.addNotify(Unknown Source)
        at java.desktop/java.awt.Container.addNotify(Unknown Source)
        at java.desktop/java.awt.Window.addNotify(Unknown Source)
        at java.desktop/java.awt.Frame.addNotify(Unknown Source)
        at java.desktop/java.awt.Window.pack(Unknown Source)
        at Game.Game.start(Unknown Source)
        at Client.Launcher.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by thelegendofbrian** [comment]
When the game loads correctly, the part around the exception should look like this

```
[ INFO] Loading file: wa.class
[ INFO] Loading file: wb.class
[ INFO] Loading resource: /assets/icon.png
[ INFO] Found logout
[ INFO] Found setLoginText
```

**Comment by thelegendofbrian** [comment]
Turns out that the issue only occurs when using Java 9. I've personally confirmed it works on Java 8.

**Comment by thelegendofbrian** [comment]
The error occurs when calling `pack()`

https://github.com/OrN/rscplus/blob/master/src/Game/Game.java#L88

**Comment by OrN** [comment]
Fixed in https://github.com/OrN/rscplus/commit/7461fbf22ba51713b53ca25af8ad1e077c0740dd
